runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GAE_ENV: "standard"
  GOOGLE_CLIENT_ID: "666989927124-dr1um1fe20bm7rs46nodrgfks3968v7u.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_DISCOVERY_URL: "https://accounts.google.com/.well-known/openid-configuration"
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://produkcjaDB:Sudomie1952Stolem@/db3dprinter?unix_socket=/cloudsql/dprintingorganiser:europe-central2:db3dprinter"
  CLOUD_STORAGE_BUCKET: "upload_3dprinting_organiser"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

instance_class: F2