"""Add accepted estimate to Project model 

Revision ID: 3753c9ed658c
Revises: 878dcf9b9e35
Create Date: 2025-02-13 17:51:30.717734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3753c9ed658c'
down_revision = '878dcf9b9e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_accepted_estimate', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('client_accepted_estimate')

    # ### end Alembic commands ###
